# Generated by Django 5.0.7 on 2024-07-31 20:08

import freshlyapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', freshlyapp.models.AppUserManager()),
            ],
        ),
    ]
