# Generated by Django 5.0.7 on 2024-07-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
