# Generated by Django 5.0.6 on 2024-10-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='PACKET', max_length=255, null=True),
        ),
    ]
