# Generated by Django 5.0.6 on 2024-10-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0002_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='product',
        ),
    ]
