# Generated by Django 5.0.6 on 2024-10-02 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0003_remove_farmer_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='phone',
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
