# Generated by Django 5.0.7 on 2024-07-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
