# Generated by Django 5.0.6 on 2024-09-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0004_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='remember_me',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
