# Generated by Django 5.0.7 on 2024-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0006_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='description',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
