# Generated by Django 5.0.7 on 2024-09-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0009_category_rename_description_product_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('description', models.CharField(max_length=1000)),
                ('aux_text', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('countdown', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='discount', max_length=255, null=True)),
            ],
        ),
    ]
