# Generated by Django 5.0.7 on 2024-09-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0010_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
