# Generated by Django 5.0.7 on 2024-09-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0011_remove_cart_product_remove_cart_quantity_cartitem'),
        ('freshlyapp', '0012_banner'),
    ]

    operations = [
    ]
