# Generated by Django 5.0.7 on 2024-09-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0014_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/Categories'),
        ),
    ]
