# Generated by Django 5.0.7 on 2024-09-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0015_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bgColor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
